name: Build Listener Clients

on: [push, pull_request, workflow_dispatch]

jobs:
  build_embedded-listener:
    name: Build Embedded Listener ${{ matrix.env }}
    strategy:
      matrix:
        env: [m5atom, m5stack-core-esp32, m5stick-c, m5stick-c-plus, ttgo-t7-v13-mini32, ttgo-t7-v14-mini32, esp32dev, esp12e, nodemcu, esp01_1m, esp07]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    #- name: Cache pip
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.cache/pip
    #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #    restore-keys: |
    #      ${{ runner.os }}-pip-
    #- name: Cache PlatformIO
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.platformio
    #    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio system info

    - name: Run PlatformIO
      run: |
        cd listener_clients/embedded-listener
        pio run -e "${{ matrix.env }}" -v
  
  analyse_blink1-listener:
    name: Analyse Blink1 Listener
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install prosepector
      run: pip install prospector[with_everything]
    - name: Analyse
      working-directory: listener_clients/blink1-listener
      run: prospector -W pyroma -0

  analyse_blinkt-listener:
    name: Analyse Pimoroni Blinkt Listener
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install prosepector
      run: pip install prospector[with_everything]
    - name: Analyse
      working-directory: listener_clients/pimoroni-blinkt-listener
      run: prospector -W pyroma -0

  analyse_gpo-listener:
    name: Analyse GPO Listener
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install prosepector
      run: pip install prospector[with_everything]
    - name: Analyse
      working-directory: listener_clients/gpo-listener
      run: prospector -W pyroma -0

  analyse_relay-listener:
    name: Analyse Relay Listener
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    #- name: Install dependencies
    #  working-directory: listener_clients/relay-listener
    #  run: |
    #    sudo apt install libudev-dev libusb-1.0-0 libusb-1.0-0-dev
    #    npm install
    #    npm install --global eslint
    #- name: Run eslint
    #  working-directory: listener_clients/relay-listener
    #  run: eslint index.js || exit 0
